@startuml
participant "User Interface" as UI
participant "Router" as Router
participant "BuildingController" as Controller
participant "BuildingService" as Service

participant "BuildingRepository" as Repository
participant "BuildingMapper" as Mapper
participant "List<BuildingListDTO>" as BuildingListDTO
participant "List<BuildingModel>" as Model

participant "Persistence" as Persistence
participant "Schema" as Schema

activate UI
UI -> Router: GET /building
activate Router
Router -> Controller: dto =\nfindAll()
activate Controller
Controller -> Service: dto =\nfindAll()
activate Service
Service -> Repository: deliveries =\nfindAll()
activate Repository
Repository -> Persistence: schemas = query()
activate Persistence
create Schema
Persistence -> Schema: schemas <<new>>
deactivate Persistence
Repository -> Mapper: deliveries = toModel(schemas)
activate Mapper
create Model
Mapper -> Model: deliveries: <<new>>
deactivate Mapper
deactivate Repository
Service -> Mapper: dto = BuildingListDTO(deliveries)
activate Mapper
create BuildingListDTO
Mapper -> BuildingListDTO: dto <<new>>
deactivate Mapper
Service --> Controller: dto
deactivate Service
Controller --> Router: dto
deactivate Controller
Router --> UI: HTTP 200 OK\njson(deliveries)
deactivate Router
deactivate UI
@enduml