@startuml
Actor "UI Gestor de frota" as User
participant "SPA" as Spa <<component>>
participant "Gestão de campus" as Controller <<component>>
activate User
User -> Spa: get passages of building floors
activate Spa
Spa -> User: request data (buildingId)

User -> Spa: adds data (buildingId)

Spa -> Controller : GET /api/buildings/:id/passages
activate Controller

Controller -> Controller : getPassagesByBuildingId(buildingId)

Controller -> Spa : OK(200) with data
deactivate Controller

Spa -> User : Shows requested data
deactivate Spa
deactivate User
@enduml
